networks:
  node-app-network:
    driver: bridge

services:
  app:
    build:
      context: ./app
    container_name: app
    networks:
      - node-app-network
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db

  db:
    build: 
      context: ./mysql
    platform: linux/x86_64
    container_name: db
    restart: always
    networks:
      - node-app-network
    environment:
      MYSQL_DATABASE: desafio
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports: 
      - '8080:80'
    depends_on:
      - app
    networks:
      - node-app-network

volumes:
  db_data:
